[dependencies]
base = "0.11.1"
accountid = "https://github.com/aviate-labs/principal.mo#main"
hex = "https://github.com/letmejustputthishere/motoko-hex#master"
canistergeek = "https://github.com/usergeek/canistergeek-ic-motoko#v0.0.3"
uuid = "https://github.com/aviate-labs/uuid.mo#v0.2.0"
icrc7-mo = "0.5.0"
icrc37-mo = "0.5.1"
vector = "0.4.1"
map = "9.0.1"
rep-indy-hash = "0.1.1"
ic-certification = "0.1.3"
class-plus = "0.0.1"
sha2 = "0.0.4"
stable-write-only = "0.1.1"
candy_0_3_0 = "https://github.com/icdevs/candy_library#v0.3.0@907a4e7363aac6c6a4e114ebc73e3d3f21e138af"
stablebuffer = "https://github.com/skilesare/StableBuffer#v0.2.0@110660769d11ba93c618dc4712525d20503bdc37"
stablebuffer_1_3_0 = "https://github.com/canscale/StableBuffer#v1.3.0@acdde6bb5b939227997cebdbb8919d2e6da8691c"
encoding_0_4_1 = "https://github.com/aviate-labs/encoding.mo#v0.4.1@2711d18727e954b11afc0d37945608512b5fbce2"
map9 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1@10b68f6ea8df5e72dfa4c07a50c8bb60a916c233"