name: cicd-mac

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/cicd-mac.yml"
      - ".github/workflows/trigger.txt"
      # Keep in sync with matrix.canister below
      - "src/funnai_backend/**"

jobs:
  smoketest:
    name: smoketest ${{ matrix.canister }}
    runs-on: macos-latest
    strategy:
      matrix:
        # Keep in sync with on.push.paths above
        canister: [funnai_backend]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Node is required for mops install
      - name: setup node
        uses: actions/setup-node@v4

      - name: install dfx
        run: |
          set -euo pipefail
          DFXVM_INIT_YES=true sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
          source "$HOME/Library/Application Support/org.dfinity.dfx/env"
          echo "$HOME/Library/Application Support/org.dfinity.dfx/bin" >> $GITHUB_PATH

      - name: install python dependencies
        run: |
          set -euo pipefail
          pip install --upgrade pip
          pip install icpp-pro

      - name: install mops to manage motoko dependencies
        run: npm install -g ic-mops

      - name: versions
        run: |
          echo "dfx version   : $(dfx --version)"
          echo "pip version   : $(pip --version)"
          echo "python version: $(python --version)"
          echo "pytest version: $(pytest --version)"

      - name: smoketest ${{ matrix.canister }} canister
        working-directory: src/${{ matrix.canister }}
        run: |
          set -euo pipefail
          mops install
          make smoketest
